### ISSUE TITLE
Addition function needs correction

### ISSUE THREAD

**Issue by fslundeen** [barnoldsrs/TeamCalculator#2]
The addition method will not respond to being called. This is probably an issue in relation to calling the method

**Comment by barnoldsrs** [comment]
I'm not seeing the addition function needing correction, as in, it isn't being invoked.  The current operator is '+', and if '+' is typed, then Return, the prompt for the two operands appears and executes as expected.

Please try to replicate the problem and if it can be reproduced reliably, attach a screenshot or other details showing how to trigger the misbehavior.
