### ISSUE TITLE
New features operators don't match spec operators

### ISSUE THREAD

**Issue by barnoldsrs** [barnoldsrs/TeamCalculator#5]
Recently added functionality is invoked using operators for area of a circle, modulo, and others.  The operators to be used were listed in a Team Calculator project document, but the code was implemented using different operators.

Even if the implemented operators seem more efficient, there could be reasons the spec'd operators were chosen, so the operators do need to match the spec.

Refer to the TeamCalculator Project Google Doc in the TeamCalculator Project assignment for the operator specification.

**Comment by fslundeen** [comment]
Corrected the operators so they matched the document.
